# Yamllint Configuration

---
ignore-from-file: .gitignore

extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-inline-mappings: true
  indentation:
    spaces: 2
    indent-sequences: true
  truthy:
    # "on" is also required by GitHub Actions for workflow trigger keyword.
    allowed-values: ["true", "false", "on"]
    check-keys: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  key-duplicates:
    forbid-duplicated-merge-keys: true
