#!/usr/bin/env bash
# sync-living-doc-reference.sh — pull a canon reference document from AbsaOSS/living-doc and
# write the local copy that agentic-toolkit's skills load.
#
# One script, one copy of the fetch / link-rewrite / provenance-header logic, driven by the
# TARGETS table below. Every file under skills/shared/references/ that mirrors living-doc canon
# is generated by this script and verified in CI (.github/workflows/test-scripts.yml) — none of
# them is hand-maintained, and a hand edit fails the build.
#
# Both canon sources live at living-doc's docs/guides/ today. A later living-doc change relocates
# guides under docs/reference/ — when that lands, update the source paths in TARGETS below (and
# the link-rewriting rules, which assume each source and its cross-references live under
# docs/guides/ and docs/examples/). The relocation affects BOTH targets, not just one.
#
# Usage:
#   scripts/sync-living-doc-reference.sh <target> <living-doc-ref>
#   scripts/sync-living-doc-reference.sh all <living-doc-ref>
#   scripts/sync-living-doc-reference.sh --list
#
# <target> is a key in TARGETS below (glossary | bdd-schemas), or "all" for every target.
# <living-doc-ref> is any git ref in AbsaOSS/living-doc: a commit SHA (required for a committed
# copy, see the 40-hex check in CI), a tag, or a branch name.
#
# Exits 1 if the target or ref is missing, the fetch fails, or the fetched file is empty.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIVING_DOC_REPO="AbsaOSS/living-doc"
REFERENCES_DIR="skills/shared/references"

# ── Target table: canon path → local path ────────────────────────────────────
# Each row is "<target>|<canon path in living-doc>|<local path relative to REPO_ROOT>".
# A plain indexed array rather than an associative one: macOS ships bash 3.2, which has no
# `declare -A`, and contributors run this script locally as well as in CI.
TARGETS=(
  "glossary|docs/guides/living-doc-glossary.md|${REFERENCES_DIR}/living-doc-glossary.md"
  "bdd-schemas|docs/guides/living-doc-header-types.md|${REFERENCES_DIR}/living-doc-bdd-schemas.md"
)

target_names() {
  local row
  for row in "${TARGETS[@]}"; do
    printf '%s\n' "${row%%|*}"
  done
}

# Echo the "<source>|<dest>" pair for a target name, or nothing if it is unknown.
target_row() {
  local row name="$1"
  for row in "${TARGETS[@]}"; do
    if [ "${row%%|*}" = "${name}" ]; then
      printf '%s' "${row#*|}"
      return 0
    fi
  done
  return 1
}

# ── Toolkit-local addenda ────────────────────────────────────────────────────
# Content that is NOT canon but that the local copy needs — pointers to files that exist only
# in this repo. Emitted verbatim at the end of the generated file, so it is reproduced byte for
# byte on every re-sync and CI's diff stays clean. Keep this strictly to toolkit-local pointers:
# anything that restates canon belongs upstream in living-doc, not here.
local_addendum() {
  case "$1" in
    bdd-schemas)
      cat <<'ADDENDUM'

---

## Toolkit-local additions

*Not part of the canon above — machine-readable contracts that live only in `agentic-toolkit`.*

**Schema reference:** for JSON schema validation, see the [schemas/](./schemas/) directory:

- [project-profile.schema.json](./schemas/project-profile.schema.json) — Project Profile validation
- [seed.schema.json](./schemas/seed.schema.json) — seed.yaml validation
- [manifest.schema.json](./schemas/manifest.schema.json) — manifest.json validation
ADDENDUM
      ;;
    *) : ;;
  esac
}

usage() {
  echo "Usage: $0 <target> <living-doc-ref>" >&2
  echo "       $0 all <living-doc-ref>" >&2
  echo "       $0 --list" >&2
  echo "  <target>: one of: $(target_names | tr '\n' ' ')| all" >&2
  echo "  <living-doc-ref>: a commit SHA, tag, or branch in ${LIVING_DOC_REPO}" >&2
}

if [ "${1:-}" = "--list" ]; then
  printf '%s\n' "${TARGETS[@]}" | tr '|' '\t'
  exit 0
fi

if [ "${1:-}" = "" ] || [ "${2:-}" = "" ]; then
  usage
  exit 1
fi

TARGET="$1"
REF="$2"

if [ "${TARGET}" != "all" ] && ! target_row "${TARGET}" >/dev/null; then
  echo "Error: unknown target '${TARGET}'" >&2
  usage
  exit 1
fi

# Percent-encode REF for safe use inside a URL path segment, preserving '/' so refs that
# contain one (e.g. "feature/foo") still address the right nested path. REF is attacker/PR
# controlled (any branch, tag, or SHA in AbsaOSS/living-doc) and is dropped unescaped into
# both the curl fetch URL and the doc links rewritten below. Reserved URL characters such as
# '#' are delimiters — curl (and a browser, for the links below) treats everything from '#'
# onward as a fragment and never sends it — so a ref containing one silently truncates the
# request instead of failing loudly. Percent-encoding leaves only unreserved characters and
# '/' in the result, so the sed replacements further down need no separate escaping either.
url_encode_ref() {
  local LC_ALL=C ref="$1" i c encoded=""
  for (( i = 0; i < ${#ref}; i++ )); do
    c="${ref:i:1}"
    case "$c" in
      [a-zA-Z0-9._~-]|/) encoded+="$c" ;;
      *) encoded+=$(printf '%%%02X' "'$c") ;;
    esac
  done
  printf '%s' "$encoded"
}

REF_URL_SAFE="$(url_encode_ref "${REF}")"

if ! [[ "${REF}" =~ ^[0-9a-f]{40}$ ]]; then
  echo "Warning: '${REF}' is not a 40-character commit SHA. A committed copy must pin an" >&2
  echo "immutable SHA — a branch name moves underneath the copy and can never be verified." >&2
  echo "CI rejects any committed reference file whose header pins a non-SHA ref." >&2
fi

TMP_FILE="$(mktemp)"
trap 'rm -f "${TMP_FILE}" "${TMP_FILE}.rewritten"' EXIT

sync_one() {
  local target="$1" row source_path dest_rel dest raw_url blob_base
  row="$(target_row "${target}")"
  source_path="${row%%|*}"
  dest_rel="${row#*|}"
  dest="${REPO_ROOT}/${dest_rel}"

  raw_url="https://raw.githubusercontent.com/${LIVING_DOC_REPO}/${REF_URL_SAFE}/${source_path}"

  echo "Fetching ${source_path} from ${LIVING_DOC_REPO}@${REF} ..." >&2
  if ! curl -fsSL --connect-timeout 10 --max-time 30 --retry 2 "${raw_url}" -o "${TMP_FILE}"; then
    echo "Error: failed to fetch ${raw_url}" >&2
    echo "Check that the ref exists and ${source_path} is still the canon path for '${target}'." >&2
    exit 1
  fi

  if [ ! -s "${TMP_FILE}" ]; then
    echo "Error: fetched file is empty — refusing to overwrite ${dest_rel}" >&2
    exit 1
  fi

  # Rewrite the canon's relative links to absolute living-doc URLs so the synced copy reads
  # correctly from inside agentic-toolkit. Same-page anchors (#section) are left untouched, as
  # are already-absolute links (http/https) — none of the patterns below can match those, since
  # each requires "(" to be followed immediately by a slash-free, colon-free relative segment.
  # Handled shapes, generic rather than a fixed filename list so a newly-added sibling doc or
  # example asset in the upstream source needs no change here:
  #   - "(../foo)"      — parent-relative, resolves under docs/ (each source lives in docs/guides/)
  #   - "(./foo)"       — explicit same-dir relative, resolves under docs/guides/
  #   - "(foo.md)"      — bare sibling filename (no path separator), resolves under docs/guides/
  #
  # REF_URL_SAFE is already percent-encoded (see above), so it contains only unreserved URL
  # characters and '/' — none of which are special to sed's s|...|...| syntax — and can be
  # dropped straight into the replacement text below with no separate escaping pass.
  blob_base="https://github.com/${LIVING_DOC_REPO}/blob/${REF_URL_SAFE}"
  sed -E \
    -e "s|\(\.\./([^)]+)\)|(${blob_base}/docs/\1)|g" \
    -e "s|\(\./([^)]+)\)|(${blob_base}/docs/guides/\1)|g" \
    -e "s|\(([A-Za-z0-9_.-]+\.md)(#[^)]*)?\)|(${blob_base}/docs/guides/\1\2)|g" \
    "${TMP_FILE}" > "${TMP_FILE}.rewritten"
  mv "${TMP_FILE}.rewritten" "${TMP_FILE}"

  {
    echo "<!-- synced from ${LIVING_DOC_REPO}@${REF} — run scripts/sync-living-doc-reference.sh ${target} ${REF} to refresh -->"
    echo "<!-- Generated file — do not edit by hand. CI re-runs the sync and fails on any diff. -->"
    echo
    cat "${TMP_FILE}"
    local_addendum "${target}"
  } > "${dest}"

  echo "Wrote $(wc -l < "${dest}") lines to ${dest_rel}" >&2
}

if [ "${TARGET}" = "all" ]; then
  for t in $(target_names); do
    sync_one "$t"
  done
else
  sync_one "${TARGET}"
fi
